# Generated by Django 4.2.6 on 2023-11-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='profilePicture',
            new_name='ProfileCarPicture',
        ),
        migrations.AddField(
            model_name='car',
            name='Picture1',
            field=models.ImageField(blank=True, upload_to='cars_picture/'),
        ),
        migrations.AddField(
            model_name='car',
            name='Picture2',
            field=models.ImageField(blank=True, upload_to='cars_picture/'),
        ),
        migrations.AddField(
            model_name='car',
            name='Picture3',
            field=models.ImageField(blank=True, upload_to='cars_picture/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Id_car',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
