# Generated by Django 4.2.6 on 2023-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='city',
            field=models.CharField(default='', max_length=58),
        ),
        migrations.AddField(
            model_name='cars',
            name='country',
            field=models.CharField(default='', max_length=42),
        ),
        migrations.AddField(
            model_name='cars',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
