# Generated by Django 4.2.6 on 2023-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_user_locarist_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='profile_picture/default_images/profile_default.jpg', upload_to='profile_picture/'),
        ),
    ]
