# Generated by Django 4.2.6 on 2023-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_profilepicture_car_profilecarpicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nb_place',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('A', 'Automatique'), ('B', 'Manuelle')], max_length=1, null=True),
        ),
    ]
