# Generated by Django 4.2.6 on 2023-11-12 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_cars_city_cars_country_cars_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('B', 'Manuelle'), ('A', 'Automatique')], max_length=1, null=True),
        ),
    ]
