# Generated by Django 4.2.6 on 2023-11-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_car_nb_place_alter_car_geardbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='geardbox',
            field=models.CharField(choices=[('B', 'Manuelle'), ('A', 'Automatique')], default='', max_length=1),
        ),
    ]
