# Generated by Django 4.2.6 on 2023-11-12 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_cars_username_alter_car_geardbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('A', 'Automatique'), ('B', 'Manuelle')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
