# Generated by Django 4.2.6 on 2023-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_user_profile_picture_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='profile_picture/default_images/profile_default.png', upload_to='profile_picture/'),
        ),
    ]
