# Generated by Django 4.2.6 on 2023-11-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_car_geardbox_alter_cars_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
