# Generated by Django 4.2.6 on 2023-11-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_cars_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.CharField(choices=[('A', 'Essence'), ('B', 'Diesel'), ('C', 'Hybride'), ('D', 'Électrique')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='cars',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('A', 'Automatique'), ('B', 'Manuelle')], max_length=1, null=True),
        ),
    ]
