# Generated by Django 4.2.6 on 2023-11-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_cars_fuel_cars_geardbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='nb_door',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='profilePicture',
            field=models.ImageField(default='profile_picture/default_images/cars.png', upload_to='cars_picture/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('B', 'Manuelle'), ('A', 'Automatique')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='geardbox',
            field=models.CharField(blank=True, choices=[('B', 'Manuelle'), ('A', 'Automatique')], max_length=1, null=True),
        ),
    ]
